version: '3.8'
services:
  mysql-springboot-container:
    image: mysql:8.0.34
    container_name: mysql-springboot-container
    ports:
      - "3310:3306"
    volumes:
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config-deamond:/etc/mysql/conf.d
    networks:
      - backend
    environment:
      MYSQL_USER: quoctoan02
      MYSQL_PASSWORD: Abc@123456789
      MYSQL_ROOT_PASSWORD: Abc@123456789
      MYSQL_DATABASE: news-app
  springboot-docker-container:
    image: quoctoan02/springboot-docker:v1.0.0
    container_name: springboot-docker-container
    ports:
      - "8085:8088"
    volumes:
      - ./:/app
    networks:
      - backend
networks:
  backend:
    name: springboot-app-network
volumes:
  mysql-springboot-data:
  mysql-springboot-config-deamond: